# Generated by Django 5.1 on 2024-09-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_security'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'securities'},
        ),
    ]
